project/urls.py
from django.contrib import admin
from django.urls import include, path

import qanda.urls
import user.urls

urlpatterns = [
    path("admin/", admin.site.urls),
    path("user/", include(user.urls, namespace="user")),
    path("", include(qanda.urls, namespace="questions")),
]

qanda/urls.py
from django.urls.conf import path

from qanda import views

app_name = "qanda"

urlpatterns = [
    path("", views.TodaysQuestionList.as_view(), name="index"),
    path("ask", views.AskQuestionView.as_view(), name="ask"),
    path(
        "daily/<int:year>/<int:month>/<int:day>/",
        views.DailyQuestionList.as_view(),
        name="daily_questions",
    ),
    path("q/search", views.SearchView.as_view(), name="question_search"),
    path("q/<int:pk>", views.QuestionDetailView.as_view(), name="question_detail"),
    path("q/<int:pk>/answer", views.CreateAnswerView.as_view(), name="answer_question"),
    path(
        "a/<int:pk>/accept",
        views.UpdateAnswerAcceptanceView.as_view(),
        name="update_answer_acceptance",
    ),
]

user/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

import user.views

app_name = "user"

urlpatterns = [
    path("login", LoginView.as_view(), name="login"),
    path("logout", LogoutView.as_view(), name="logout"),
    path("register", user.views.RegisterView.as_view(), name="register"),
]

qanda/models.py
from django.conf import settings
from django.db import models
from django.urls.base import reverse

from qanda.service import elasticsearch


class Question(models.Model):
    title = models.CharField(max_length=140)
    question = models.TextField()
    user = models.ForeignKey(to=settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

    def save(
        self, force_insert=False, force_update=False, using=None, update_fields=None
    ):
        super().save(
            force_insert=force_insert,
            force_update=force_update,
            using=using,
            update_fields=update_fields,
        )
        elasticsearch.upsert(self)

    def get_absolute_url(self):
        return reverse("qanda:question_detail", kwargs={"pk": self.id})

    def can_accept_answers(self, user):
        return user == self.user

    def as_elasticsearch_dict(self):
        return {
            "_id": self.id,
            "_type": "doc",
            "text": "{}\n{}".format(self.title, self.question),
            "question_body": self.question,
            "title": self.title,
            "id": self.id,
            "created": self.created,
        }


class Answer(models.Model):
    answer = models.TextField()
    user = models.ForeignKey(to=settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)
    question = models.ForeignKey(to=Question, on_delete=models.CASCADE)
    accepted = models.BooleanField(default=False)

    class Meta:
        ordering = ("-created",)

project/qanda/forms.py
from django import forms
from django.contrib.auth import get_user_model

from qanda.models import Question, Answer


class AnswerAcceptanceForm(forms.ModelForm):
    accepted = forms.BooleanField(widget=forms.HiddenInput, required=False)

    class Meta:
        model = Answer
        fields = ["accepted"]


class AnswerForm(forms.ModelForm):
    user = forms.ModelChoiceField(
        widget=forms.HiddenInput, queryset=get_user_model().objects.all(), disabled=True
    )
    question = forms.ModelChoiceField(
        widget=forms.HiddenInput, queryset=Question.objects.all(), disabled=True
    )

    class Meta:
        model = Answer
        fields = ["answer", "user", "question"]


class QuestionForm(forms.ModelForm):
    user = forms.ModelChoiceField(
        widget=forms.HiddenInput, queryset=get_user_model().objects.all(), disabled=True
    )

    class Meta:
        model = Question
        fields = ["title", "question", "user"]

qanda/forms.py
from django import forms
from django.contrib.auth import get_user_model

from qanda.models import Answer, Question


class AnswerAcceptanceForm(forms.ModelForm):
    accepted = forms.BooleanField(widget=forms.HiddenInput, required=False,)

    class Meta:
        model = Answer
        fields = [
            "accepted",
        ]


class AnswerForm(forms.ModelForm):
    user = forms.ModelChoiceField(
        widget=forms.HiddenInput,
        queryset=get_user_model().objects.all(),
        disabled=True,
    )
    question = forms.ModelChoiceField(
        widget=forms.HiddenInput, queryset=Question.objects.all(), disabled=True,
    )

    class Meta:
        model = Answer
        fields = [
            "answer",
            "user",
            "question",
        ]


class QuestionForm(forms.ModelForm):
    user = forms.ModelChoiceField(
        widget=forms.HiddenInput,
        queryset=get_user_model().objects.all(),
        disabled=True,
    )

    class Meta:
        model = Question
        fields = [
            "title",
            "question",
            "user",
        ]

project/qanda/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http.response import HttpResponseRedirect, HttpResponseBadRequest
from django.urls.base import reverse
from django.urls import reverse_lazy
from django.utils import timezone
from django.views.generic import (
    CreateView,
    DayArchiveView,
    DetailView,
    RedirectView,
    UpdateView,
    TemplateView,
)

from qanda.service.elasticsearch import search_for_questions
from qanda.forms import QuestionForm, AnswerForm, AnswerAcceptanceForm
from qanda.models import Question, Answer


class AskQuestionView(LoginRequiredMixin, CreateView):
    form_class = QuestionForm
    template_name = "qanda/ask.html"

    def get_initial(self):
        return {"user": self.request.user.id}

    def get_success_url(self):
        return reverse_lazy("qanda:index")

    def form_valid(self, form):
        action = self.request.POST.get("action")
        if action == "SAVE":
            # save and redirect as usual.
            return super().form_valid(form)
        elif action == "PREVIEW":
            preview = Question(
                question=form.cleaned_data["question"], title=form.cleaned_data["title"]
            )
            ctx = self.get_context_data(preview=preview)
            return self.render_to_response(context=ctx)
        return HttpResponseBadRequest()


class CreateAnswerView(LoginRequiredMixin, CreateView):
    form_class = AnswerForm
    template_name = "qanda/create_answer.html"

    def get_initial(self):
        return {
            "question": self.get_question().id,
            "user": self.request.user.id,
        }

    def get_context_data(self, **kwargs):
        return super().get_context_data(question=self.get_question(), **kwargs)

    def get_success_url(self):
        return self.object.question.get_absolute_url()

    def form_valid(self, form):
        action = self.request.POST.get("action")
        if action == "SAVE":
            # save and redirect as usual.
            return super().form_valid(form)
        elif action == "PREVIEW":
            ctx = self.get_context_data(preview=form.cleaned_data["answer"])
            return self.render_to_response(context=ctx)
        return HttpResponseBadRequest()

    def get_question(self):
        return Question.objects.get(pk=self.kwargs["pk"])


class DailyQuestionList(DayArchiveView):
    queryset = Question.objects.all()
    date_field = "created"
    month_format = "%m"
    allow_empty = True


class QuestionDetailView(DetailView):
    model = Question

    ACCEPT_FORM = AnswerAcceptanceForm(initial={"accepted": True})
    REJECT_FORM = AnswerAcceptanceForm(initial={"accepted": False})

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        ctx.update(
            {
                "answer_form": AnswerForm(
                    initial={"user": self.request.user.id, "question": self.object.id}
                )
            }
        )
        if self.object.can_accept_answers(self.request.user):
            ctx.update(
                {"accept_form": self.ACCEPT_FORM, "reject_form": self.REJECT_FORM}
            )
        return ctx


class SearchView(TemplateView):
    template_name = "qanda/search.html"

    def get_context_data(self, **kwargs):
        query = self.request.GET.get("q", None)
        ctx = super().get_context_data(query=query, **kwargs)
        if query:
            results = search_for_questions(query)
            ctx["hits"] = results
        return ctx


class TodaysQuestionList(RedirectView):
    def get_redirect_url(self, *args, **kwargs):
        today = timezone.now()
        return reverse(
            "questions:daily_questions",
            kwargs={"day": today.day, "month": today.month, "year": today.year},
        )


class UpdateAnswerAcceptanceView(LoginRequiredMixin, UpdateView):
    form_class = AnswerAcceptanceForm
    queryset = Answer.objects.all()

    def get_success_url(self):
        return self.object.question.get_absolute_url()

    def form_invalid(self, form):
        return HttpResponseRedirect(redirect_to=self.object.question.get_absolute_url())

qanda/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http.response import HttpResponseBadRequest, HttpResponseRedirect
from django.urls.base import reverse
from django.utils import timezone
from django.views.generic import (CreateView, DayArchiveView, DetailView,
                                  RedirectView, TemplateView, UpdateView)

from qanda.forms import AnswerAcceptanceForm, AnswerForm, QuestionForm
from qanda.models import Answer, Question
from qanda.service.elasticsearch import search_for_questions


class AskQuestionView(LoginRequiredMixin, CreateView):
    form_class = QuestionForm
    template_name = "qanda/ask.html"

    def get_initial(self):
        return {"user": self.request.user.id}

    def form_valid(self, form):
        action = self.request.POST.get("action")
        if action == "SAVE":
            # save and redirect as usual.
            return super().form_valid(form)
        elif action == "PREVIEW":
            preview = Question(
                question=form.cleaned_data["question"], title=form.cleaned_data["title"]
            )
            ctx = self.get_context_data(preview=preview)
            return self.render_to_response(context=ctx)
        return HttpResponseBadRequest()


class CreateAnswerView(LoginRequiredMixin, CreateView):
    form_class = AnswerForm
    template_name = "qanda/create_answer.html"

    def get_initial(self):
        return {
            "question": self.get_question().id,
            "user": self.request.user.id,
        }

    def get_context_data(self, **kwargs):
        return super().get_context_data(question=self.get_question(), **kwargs)

    def get_success_url(self):
        return self.object.question.get_absolute_url()

    def form_valid(self, form):
        action = self.request.POST.get("action")
        if action == "SAVE":
            # save and redirect as usual.
            return super().form_valid(form)
        elif action == "PREVIEW":
            ctx = self.get_context_data(preview=form.cleaned_data["answer"])
            return self.render_to_response(context=ctx)
        return HttpResponseBadRequest()

    def get_question(self):
        return Question.objects.get(pk=self.kwargs["pk"])


class DailyQuestionList(DayArchiveView):
    queryset = Question.objects.all()
    date_field = "created"
    month_format = "%m"
    allow_empty = True


class QuestionDetailView(DetailView):
    model = Question

    ACCEPT_FORM = AnswerAcceptanceForm(initial={"accepted": True})
    REJECT_FORM = AnswerAcceptanceForm(initial={"accepted": False})

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        ctx.update(
            {
                "answer_form": AnswerForm(
                    initial={"user": self.request.user.id, "question": self.object.id,}
                )
            }
        )
        if self.object.can_accept_answers(self.request.user):
            ctx.update(
                {"accept_form": self.ACCEPT_FORM, "reject_form": self.REJECT_FORM,}
            )
        return ctx


class SearchView(TemplateView):
    template_name = "qanda/search.html"

    def get_context_data(self, **kwargs):
        query = self.request.GET.get("q", None)
        ctx = super().get_context_data(query=query, **kwargs)
        if query:
            results = search_for_questions(query)
            ctx["hits"] = results
        return ctx


class TodaysQuestionList(RedirectView):
    def get_redirect_url(self, *args, **kwargs):
        today = timezone.now()
        return reverse(
            "questions:daily_questions",
            kwargs={"day": today.day, "month": today.month, "year": today.year,},
        )


class UpdateAnswerAcceptanceView(LoginRequiredMixin, UpdateView):
    form_class = AnswerAcceptanceForm
    queryset = Answer.objects.all()

    def get_success_url(self):
        return self.object.question.get_absolute_url()

    def form_invalid(self, form):
        return HttpResponseRedirect(redirect_to=self.object.question.get_absolute_url())

qanda/templates/qanda/ask.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% load markdownify %}
{% load crispy_forms_tags %}

{% block title %} Ask a question {% endblock %}

{% block body %}
    <div class="row">
        <div class="col-md-12">
            <h1>Ask a question</h1>
            {% if preview %}
                <div class="card question-preview">
                    <div class="card-header">
                        Question Preview
                    </div>
                    <div class="card-body">
                        <h1 class="card-title">{{ preview.title }}</h1>
                        {{ preview.question |  markdownify }}
                    </div>
                </div>
            {% endif %}

            <form method="POST" novalidate>
                {{ form|crispy }}
                {% csrf_token %}
                <button class="btn btn-outline-primary btn-sm" id="preview"
                        type="submit" name="action" value="PREVIEW">
                    Preview
                </button>
                <button class="btn btn-outline-primary btn-sm" id='ask' type="submit"
                        name="action" value="SAVE">Ask!
                </button>
            </form>
        </div>
    </div>
{% endblock %}

qanda/templates/qanda/create_answer.html
{% extends "base.html" %}
{% load markdownify %}

{% block body %}
    {% include 'qanda/common/display_question.html' %}
    {% if preview %}
        <div class="card question-preview">
            <div class="card-header">
                Answer Preview
            </div>
            <div class="card-body">
                {{ preview|markdownify }}
            </div>
        </div>
    {% endif %}
    {% include 'qanda/common/post_answer.html' with answer_form=form %}
{% endblock %}

qanda/templates/qanda/question_archive_day.html
{% extends "base.html" %}
{% load static %}

{% block title %} Questions on {{ day }} {% endblock %}

{% block body %}
    <div class="row">
        <div class="col-md-8">
            <h1>Highest Voted Questions of {{ day }}</h1>
            <ul>
                {% for question in object_list %}
                    <li>
                        {{ question.votes }}
                        <a href="{{ question.get_absolute_url }}">{{ question }}</a>
                        by {{ question.user }}
                        on {{ question.created|date:"Y-m-d H:i" }}
                    </li>
                {% empty %}
                    <li>No news today.</li>
                {% endfor %}
            </ul>
            <div>
                {% if previous_day %}
                    <a href="{% url "qanda:daily_questions" year=previous_day.year month=previous_day.month day=previous_day.day %}"
                       class="btn btn-outline-success btn-sm">
                        &laquo; Previous Day
                    </a>
                {% endif %}
                {% if next_day %}
                    <a href="{% url "qanda:daily_questions" year=next_day.year month=next_day.month day=next_day.day %}"
                       class="btn btn-outline-success btn-sm">
                        Next Day &raquo;
                    </a>
                {% endif %}
            </div>
        </div>
        <div class="col-md-4">
            <img src="{% static "img/ufo.svg" %}" alt="img" class="ufo">
        </div>
    </div>
{% endblock %}

qanda/templates/qanda/question_detail.html
{% extends "base.html" %}

{% block title %}{{ question.title }} - {{ block.super }}{% endblock %}

{% block body %}
    {% include "qanda/common/display_question.html" %}
    {% include "qanda/common/list_answers.html" %}
    {% if user.is_authenticated %}
        {% include "qanda/common/post_answer.html" %}
    {% else %}
        <div class="col-md-8 offset-md-2"><p class="mt-5 text-center">Login to post answers.</p></div>
    {% endif %}
{% endblock %}

qanda/templates/qanda/search.html
{% extends "base.html" %}

{% load markdownify %}

{% block body %}
    <div class="row">
        <div class="col-md-12">
            <h1>Search</h1>
            <form method="GET" class="form-inline" novalidate>
                <input class="form-control mr-2" placeholder="Search" type="search"
                       name="q" value="{{ query }}">
                <button type="submit" class="btn btn-outline-success">Search</button>
            </form>
            {% if query %}
                <h2 class="mt-3">Results from search query '{{ query }}'</h2>
                <ul class="list-unstyled search-results">
                    {% for hit in hits %}
                        <li>
                            <a href="{% url "qanda:question_detail" pk=hit.id %}">
                                {{ hit.title }}
                            </a>
                            <div>
                                {{ hit.question_body|markdownify|truncatewords_html:20 }}
                            </div>
                        </li>
                    {% empty %}
                        <li>No results.</li>
                    {% endfor %}
                </ul>
            {% endif %}
        </div>
    </div>
{% endblock %}