project/urls.py
from django.contrib import admin
from django.urls import include, path

import qanda.urls
import user.urls

urlpatterns = [
    path("admin/", admin.site.urls),
    path("user/", include(user.urls, namespace="user")),
    path("", include(qanda.urls, namespace="questions")),
]

qanda/urls.py
from django.urls.conf import path

from qanda import views

app_name = "qanda"

urlpatterns = [
    path("", views.TodaysQuestionList.as_view(), name="index"),
    path("ask", views.AskQuestionView.as_view(), name="ask"),
    path(
        "daily/<int:year>/<int:month>/<int:day>/",
        views.DailyQuestionList.as_view(),
        name="daily_questions",
    ),
    path("q/search", views.SearchView.as_view(), name="question_search"),
    path("q/<int:pk>", views.QuestionDetailView.as_view(), name="question_detail"),
    path("q/<int:pk>/answer", views.CreateAnswerView.as_view(), name="answer_question"),
    path(
        "a/<int:pk>/accept",
        views.UpdateAnswerAcceptanceView.as_view(),
        name="update_answer_acceptance",
    ),
]

user/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

import user.views

app_name = "user"

urlpatterns = [
    path("login", LoginView.as_view(), name="login"),
    path("logout", LogoutView.as_view(), name="logout"),
    path("register", user.views.RegisterView.as_view(), name="register"),
]

templates/includes/footer.html
<footer class="footer mt-5">
    <div class="container">
        <div class="row pt-5">
            <div class="col-md-6 offset-md-3 text-center">
                <h3>We <3 people who code</h3>
                <p>We build products that empower developers and connect them to
                    solutions that enable productivity, growth, and discovery.</p>
            </div>
        </div>
        <div class="row mb-2 mt-5 text-center">
            <div class="col-md-6">
                <h4>Reach developers worldwide</h4>
                <p>Use the world’s largest resource for people who code to help you
                    increase awareness and showcase your product or service across
                    Django Overflow’s network of Q&A sites.
                </p>
            </div>
            <div class="col-md-6">
                <h4>Support open source</h4>
                <p>Reach users of your project by following tags, answering newcomer
                    questions, and empowering experts in the community.</p>
            </div>
        </div>
    </div>
</footer>

templates/includes/nav.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'qanda:index' %}">Django Overflow</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
      {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'user:logout' %}">Logout</a>
                </li>
            {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'user:login' %}">Login</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'user:register' %}">Register</a>
                </li>
            {% endif %}
      </ul>
      <form class="d-flex" action="{% url 'qanda:question_search' %}" method="GET">
        <input class="form-control me-2" type="search" name="q" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>